import { Providers } from '@/redux/provider'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className={montserrat.className}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
