import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";

import { RootProvider } from "./providers";

import type { Metadata } from "next";

import "react-toastify/dist/ReactToastify.css";

const montserrat = Montserrat({
  subsets: ["cyrillic", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={montserrat.className}>
      <body>
        <RootProvider>{children}</RootProvider>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
